"""Authentication handlers for Petstore API.

Auto-generated by MCP Toolbox v0.2.0.
"""

from __future__ import annotations

from collections.abc import Generator

import httpx


class APIKeyHeaderAuth(httpx.Auth):
    """Attach API key via custom request header."""

    def __init__(self, header_name: str, api_key: str) -> None:
        self.header_name = header_name
        self.api_key = api_key

    def auth_flow(self, request: httpx.Request) -> Generator[httpx.Request, None, None]:
        """Inject API key header into outgoing request."""

        request.headers[self.header_name] = self.api_key
        yield request
