"""Pydantic models for Petstore API MCP server.

Auto-generated by MCP Toolbox v0.2.0.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class Error(BaseModel):
    """Error schema model."""

    model_config = ConfigDict(
        populate_by_name=True,
    )

    code: int
    message: str


class NewPet(BaseModel):
    """NewPet schema model."""

    model_config = ConfigDict(
        populate_by_name=True,
    )

    name: str = Field(..., description="Pet display name.")
    tag: str | None = Field(None, description="Optional pet tag.")
    status: Literal["available", "pending", "sold"] | None = Field(None, description="Current pet status.")


class Order(BaseModel):
    """Order schema model."""

    model_config = ConfigDict(
        populate_by_name=True,
    )

    id: str
    pet_id: str = Field(..., alias="petId")
    quantity: int
    status: Literal["pending", "completed", "cancelled"]


class Pet(BaseModel):
    """Pet schema model."""

    model_config = ConfigDict(
        populate_by_name=True,
    )

    id: str = Field(..., description="Unique pet identifier.")
    name: str = Field(..., description="Pet display name.")
    tag: str | None = Field(None, description="Optional pet tag.")
    status: Literal["available", "pending", "sold"] | None = Field(None, description="Current pet status.")


Error.model_rebuild()
NewPet.model_rebuild()
Order.model_rebuild()
Pet.model_rebuild()
