"""Petstore API MCP Server.

Auto-generated by MCP Toolbox v0.2.0 from OpenAPI spec.
Do not edit manually — regenerate with: mcp-toolbox generate --spec <your-spec>
"""

from __future__ import annotations

import os
from contextlib import asynccontextmanager
from dataclasses import dataclass
from typing import Any, Literal

import httpx
from mcp.server.fastmcp import FastMCP

from .auth import APIKeyHeaderAuth
from .client import build_client, load_client_settings
from .models import Order, Pet
from .tools.create_pet import create_pet_impl
from .tools.delete_pet import delete_pet_impl
from .tools.get_pet_by_id import get_pet_by_id_impl
from .tools.list_orders import list_orders_impl
from .tools.list_pets import list_pets_impl
from .tools.update_pet import update_pet_impl


@dataclass
class AppContext:
    """Shared application context available to all tools via lifespan."""

    client: httpx.AsyncClient
    max_retries: int
    backoff_seconds: float
    retry_unsafe_methods: bool


@asynccontextmanager
async def app_lifespan(server: FastMCP):
    """Initialize shared HTTP client with auth and connection pooling."""

    del server

    base_url = os.environ.get("PETSTORE_API_BASE_URL", "https://api.petstore.example.com/v1")
    auth_handler: httpx.Auth | None = None

    api_key = os.environ.get("PETSTORE_API_API_KEY", "")
    auth_handler = APIKeyHeaderAuth("X-API-Key", api_key) if api_key else None

    settings = load_client_settings("PETSTORE_API")

    async with build_client(base_url=base_url, settings=settings, auth=auth_handler) as client:
        yield AppContext(
            client=client,
            max_retries=settings.max_retries,
            backoff_seconds=settings.backoff_seconds,
            retry_unsafe_methods=settings.retry_unsafe_methods,
        )


mcp = FastMCP(
    name="Petstore API",
    instructions="API for managing pets and store orders.",
    lifespan=app_lifespan,
)

PAGINATION_HINTS: dict[str, str] = {
    "list_pets": "offset_limit",
}


def get_pagination_hints() -> dict[str, str]:
    """Return detected pagination patterns for generated tools.

    Patterns:
    - ``offset_limit``: uses `limit` + `offset`
    - ``page_per_page``: uses `page` + `per_page`
    - ``cursor``: uses cursor token parameter
    - ``link_header`` / ``page_header`` / ``cursor_header``: response header hints
    - ``page_body`` / ``cursor_body``: response body hints
    """

    return dict(PAGINATION_HINTS)


# --- list_pets ---
@mcp.tool(structured_output=True)
async def list_pets(limit: int | None = 20, offset: int | None = 0) -> list[Pet]:
    """List pets"""

    ctx: AppContext = mcp.get_context().request_context.lifespan_context
    return await list_pets_impl(ctx, limit, offset)


# --- get_pet_by_id ---
@mcp.tool(structured_output=True)
async def get_pet_by_id(pet_id: str) -> Pet:
    """Get pet by ID"""

    ctx: AppContext = mcp.get_context().request_context.lifespan_context
    return await get_pet_by_id_impl(ctx, pet_id)


# --- list_orders ---
@mcp.tool(structured_output=True)
async def list_orders(status: Literal["pending", "completed", "cancelled"] | None = None) -> list[Order]:
    """List store orders"""

    ctx: AppContext = mcp.get_context().request_context.lifespan_context
    return await list_orders_impl(ctx, status)


# --- create_pet ---
@mcp.tool(structured_output=True)
async def create_pet(
    name: str, tag: str | None = None, status: Literal["available", "pending", "sold"] | None = None
) -> Pet:
    """Create a pet"""

    ctx: AppContext = mcp.get_context().request_context.lifespan_context
    return await create_pet_impl(ctx, name, tag, status)


# --- update_pet ---
@mcp.tool(structured_output=True)
async def update_pet(
    pet_id: str, name: str, tag: str | None = None, status: Literal["available", "pending", "sold"] | None = None
) -> Pet:
    """Update an existing pet"""

    ctx: AppContext = mcp.get_context().request_context.lifespan_context
    return await update_pet_impl(ctx, pet_id, name, tag, status)


# --- delete_pet ---
@mcp.tool()
async def delete_pet(pet_id: str) -> Any:
    """Delete pet by ID"""

    ctx: AppContext = mcp.get_context().request_context.lifespan_context
    return await delete_pet_impl(ctx, pet_id)


def main() -> None:
    """Entry point for the generated MCP server."""

    import sys

    transport = "stdio"
    if "--transport" in sys.argv:
        idx = sys.argv.index("--transport")
        if idx + 1 < len(sys.argv):
            transport = sys.argv[idx + 1]

    mcp.run(transport=transport)


if __name__ == "__main__":
    main()
